ignores:
  - '@swc/core'
  - '@graphql-codegen/*'
  # Aliases
  - '@abi/*'
  - '@app/*'
  - '@components/*'
  - '@graphql/*'
  - '@grpc/*'
  - '@hooks/*'
  - '@lib/*'
  - '@public/*'
  - '@state/*'
  - '@styles/*'
  - '@tests/*'
  - '@utils/*'
  - '@data/*'
  # Apollo
  - apollo-server-types
  - graphql-tag
  - standard-commit
  - tsconfig-paths
  - wait-on
  # Build
  - '@babel/' # Babel plugins
  - '@babel/preset-env'
  - babel-loader
  - autoprefixer
  - depcheck
  - esbuild
  - '@ethersproject/bytes'
  - react-is
  - '@trivago/prettier-plugin-sort-imports'
  - '@vue/compiler-sfc'
  # CLI
  - rimraf
